### ISSUE TITLE
Wrong delete method

### ISSUE THREAD

**Issue by qhu91it** [SudhindraAnegondhi/cloud_firestore_rest#2]
Hi, I found in delete function using put method so it can not delete collection, should be change to delete method

https://github.com/SudhindraAnegondhi/cloud_firestore_rest/blob/850b202cd61c85a7c771a506250fc067fb4de0af/lib/cloud_firestore_rest.dart#L347

**Comment by SudhindraAnegondhi** [comment]
Thank you. Just rectified it.
